name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Add permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js and Dependencies
      uses: ./.github/actions/setup-node-deps
      with:
        node-version: '20'
      
    - name: Build
      run: |
        echo "Building React app..."
        yarn build
        echo "Build completed. Checking build directory..."
        ls -la build/
      env:
        # Use the client ID from secrets or a placeholder for PR builds
        REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID || 'placeholder-client-id' }}
        
    - name: Setup Pages
      if: github.ref == 'refs/heads/master'
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      if: github.ref == 'refs/heads/master'
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./build

  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
